apiVersion : apps/v1
kind: Deployment
metadata:
  name: "template-for-aa-1127" 
spec:
  replicas: 1
  selector:
    matchLabels:
      app: "template-for-aa-1127"
  template:
    metadata:
      labels:
        app: "template-for-aa-1127" 
    spec:
      containers:
        - name: "template-for-aa-1127" 
          image: cepgstapacr.azurecr.io/template-for-aa-1127
          ports:
          - containerPort: 8080
