apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: template-for-aa-1127-ingress
spec:
  rules:
  - host: template-for-aa-1127.ce-aa.kubepia.net
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: my-template-for-aa-1127
            port:
              number: 80
