configMapGenerator:
- files:
  - application.yml
  name: "template-for-aa-1127-configmap"
resources:
- ../../base
- pvc.yaml
patchesStrategicMerge:
- deployment.yaml
- ingress.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namePrefix: prod-
images:
- name: cepgstapacr.azurecr.io/template-for-aa-1127
  newTag: "202408090453"

